name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Flake8
        run: pip install flake8
      - name: Lint API with Flake8
        working-directory: ./api
        run: flake8 .
      - name: Lint Worker with Flake8
        working-directory: ./worker
        run: flake8 .
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Lint Frontend with ESLint
        working-directory: ./frontend
        run: npx eslint .
